### ISSUE TITLE
[Epic] 2022-1 (Semester 1)

### ISSUE THREAD

**Issue by winstonsung** [tkuaiic/tkuaiic-board-2022#2]
- [ ] https://github.com/tkuaiic/tkuaiic-boards-2022/issues/3
- [ ] https://github.com/tkuaiic/tkuaiic-boards-2022/issues/4
- [ ] https://github.com/tkuaiic/tkuaiic-boards-2022/issues/5
- [ ] https://github.com/tkuaiic/tkuaiic-boards-2022/issues/6
- [ ] https://github.com/tkuaiic/tkuaiic-boards-2022/issues/7
